# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e1ec5e860171288ae6d2eb2ad5d454b3ee3a45e0d22808b65c55469b92cf2b2371431e3b088ae346e7f069b0b6274bb5176fd6245bf3d186fa4d953ec734e43

test:
  secret_key_base: d623dde4db684519593bd54e745951dd0323110bce3bbddf1ebd3efcc79010883c5b42c0c01400e626bd4940933a85faeb1d9b345c713694ab24b9435c4aa6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
